### ISSUE TITLE
一些疑问需要您指点

### ISSUE THREAD

**Issue by Relax-87** [geniucker-dev/WalletFix4OOS14#1]
首先非常感谢您的付出，这对有nfc门禁卡方面的人群非常有参考和实用价值。
但从您的readme概述中有以下几点想请您明确指出一些操作式，这样有助于帮助更多我们这样小白。

1、该流程操作是否需要root？

2、安装Oppo钱包 这个通过什么方式可以得到？
我已经在很多地方找oppo钱包 尚未找到也许方式不对。或者提取？或者您的项目中已经包含？

3、system.prop中的ro.product.model字段改为对应机型的国行机型编号
这句话意味着我们需要重新编译apk吗？还是直接按装您的 Releases？

4、我看到项目中的product/priv-app目录下有很多 apk 我们都需要安装还是有别的使用方法？

**Comment by geniucker-dev** [comment]
1. 首先这是一个Magisk/KernelSU/Apatch模块，所以需要root，目前仅在KernelSU上进行了测试
2. 钱包app可以直接从oppo的应用商店下载安装 https://store.oppomobile.com/m/store.html
3. 这并不是个apk，若要修改机型编号，只需要修改release包中的对应文件，模块就是个zip文件
4. 安装完模块就会自动把缺失的几个应用安装为系统应用，不需要手动操作

另外，这个模块并不完善，只是达到了能用的程度。全局修改机型编号会导致一些奇怪的问题。
从你问的问题来看，你并不熟悉magisk模块，因此不建议使用

**Comment by Relax-87** [comment]
> 1. 首先这是一个Magisk/KernelSU/Apatch模块，所以需要root，目前仅在KernelSU上进行了测试
> 2. 钱包app可以直接从oppo的应用商店下载安装 https://store.oppomobile.com/m/store.html
> 3. 这并不是个apk，若要修改机型编号，只需要修改release包中的对应文件，模块就是个zip文件
> 4. 安装完模块就会自动把缺失的几个应用安装为系统应用，不需要手动操作
> 
> 另外，这个模块并不完善，只是达到了能用的程度。全局修改机型编号会导致一些奇怪的问题。 从你问的问题来看，你并不熟悉magisk模块，因此不建议使用

感谢您的解答，我已经很多年没有对手机进行root操作了，对于现在新时代的手机root确实不太了解。因为某些原因我还是比较避讳root这件事情，我参考了很多方案，都说需要magisk模块进行安装我还是准备放弃了 就这么凑活用了。还是非常感谢您的解答。
